Hometask 1
Irychhh/teamcity-testing-framework pull request #1
Opened 2023-12-04 10:30 UTC by Irychhh

2023-12-08 18:56 UTC, AlexPshe commented
Привет! 

Большое спасибо за качественное выполнение задания! 

Я добавила несколько комментов по улучшению - нужно пофиксить их за неделю и будет зачтено ⚡️

2023-12-08 22:23 UTC, Irychhh commented
@AlexPshe Саша, привет! Спасибо за похвалу, это очень приятно! Прости за глупый вопрос - а где комментарии смотреть?)) Не увидела тут.. Или у меня какая-то настройка не включена или я не понимать

2023-12-08 22:33 UTC, AlexPshe requested changes

2023-12-08 22:33 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/CreateBuildConfigurationTest.java
> +                {"SYSTEM_ADMIN"},
Давай создадим тут Enum, чтобы мы не допустили ошибку слуйчано при ручном наборе констант 👌

2023-12-08 22:33 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/CreateBuildConfigurationTest.java
> +                .body(Matchers.containsString("Project cannot be found by external id '" + testId + "'."));
Можно тут использовать `format`, чтобы более красиво вставлять значение внутри строчки 👌

2023-12-08 22:33 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/CreateProjectTest.java
> +    private final String EMPTY_NAME_ERROR = "Project name cannot be empty.";
Выглядит как то, что нам нужен отдельный статический класс или enumeration с текстами ошибок для API, а если наши автотесты рядом с кодом API, можно эти тексты забрать прямо из кода API 🙌

2023-12-08 22:33 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/CreateProjectTest.java
> +        var updatedProject = uncheckedWithSuperUser.getProjectRequest()
Выглядит так, что мы можем заменить этот вызов на использование `checkedWithSuperUser.getProjectRequest()`

2023-12-08 22:33 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/CreateProjectTest.java
> +
Форматинг: лишняя строка

2023-12-08 22:33 UTC, AlexPshe commented on src/test/java/com/example/teamcity/api/CreateBuildConfigurationTest.java
> +        uncheckedWithSuperUser.getBuildConfigRequest()
А как насчет вместо создания новой сущности, поменять в testData айдишник у `buildType.getProject().setId()`

2023-12-08 22:33 UTC, AlexPshe commented
> @AlexPshe Саша, привет! Спасибо за похвалу, это очень приятно! Прости за глупый вопрос - а где комментарии смотреть?)) Не увидела тут.. Или у меня какая-то настройка не включена или я не понимать

А сейчас видно?) Кажется до этого я не была ревьюером, но сейчас добавилась

2023-12-08 23:56 UTC, Irychhh commented
> > @AlexPshe Саша, привет! Спасибо за похвалу, это очень приятно! Прости за глупый вопрос - а где комментарии смотреть?)) Не увидела тут.. Или у меня какая-то настройка не включена или я не понимать
> 
> А сейчас видно?) Кажется до этого я не была ревьюером, но сейчас добавилась

Да! вот сейчас вижу их)) спасибище

2023-12-15 23:33 UTC, Irychhh commented on src/test/java/com/example/teamcity/api/CreateBuildConfigurationTest.java
> +                {"SYSTEM_ADMIN"},
переиспользовала Role  во всех датапровайдерах

2023-12-15 23:33 UTC, Irychhh commented on src/test/java/com/example/teamcity/api/CreateBuildConfigurationTest.java
> +                .body(Matchers.containsString("Project cannot be found by external id '" + testId + "'."));
исправила тут и в остальных)

2023-12-15 23:34 UTC, Irychhh commented on src/test/java/com/example/teamcity/api/CreateProjectTest.java
> +    private final String EMPTY_NAME_ERROR = "Project name cannot be empty.";
вынесла константы в enumeration ApiErrorMessages)

2023-12-15 23:34 UTC, Irychhh commented on src/test/java/com/example/teamcity/api/CreateProjectTest.java
> +        var updatedProject = uncheckedWithSuperUser.getProjectRequest()
поправила

2023-12-15 23:34 UTC, Irychhh commented on src/test/java/com/example/teamcity/api/CreateProjectTest.java
> +
+

2023-12-15 23:35 UTC, Irychhh commented on src/test/java/com/example/teamcity/api/CreateBuildConfigurationTest.java
> +        uncheckedWithSuperUser.getBuildConfigRequest()
точно)) поправила

2023-12-15 23:36 UTC, Irychhh commented
@AlexPshe Саша, привет! все пофиксила)

2024-02-13 09:13 UTC, Irychhh commented
Запушу эту ветку

2024-02-13 09:20 UTC, merged