Hometask 3
Irychhh/teamcity-testing-framework pull request #2
Opened 2024-02-10 00:14 UTC by Irychhh

2024-02-13 02:38 UTC, AlexPshe requested changes
Привет! 

Почему-то не вижу всех изменений в пулл реквесте, выглядит, как-будто часть изменений пришли из другой ветки, можешь посмотреть, пожалуйста?

2024-02-13 09:13 UTC, Irychhh commented
> Привет!
> 
> Почему-то не вижу всех изменений в пулл реквесте, выглядит, как-будто часть изменений пришли из другой ветки, можешь посмотреть, пожалуйста?

Саша, привет! У меня часть в основной ветке main оказалась, правда( я поменяла ветку, в которую нужно замержить, посмотри теперь пожалуйста.

2024-02-13 20:34 UTC, AlexPshe requested changes
Привет! 

Отлично, давай поправим один коммент и будет зачтено ⚡️

2024-02-14 08:10 UTC, Irychhh commented on src/main/java/com/example/teamcity/ui/pages/AgentAuthPage.java
> +        Selenide.open("/agents/unauthorized");
Просто по аналогии с startUpTest сделала, к тому же эти два теста в одном классе в /ui живут) Потом уже появилась инфа, что можно сделать через api, сразу я не догадалась)

2024-02-15 12:49 UTC, AlexPshe approved these changes
Теперь все отлично, зачтено ⚡️

2024-02-25 20:00 UTC, merged